name: Add Bookmark

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL (article, post, podcast, etc.)"
        required: true
        type: string
      commentary:
        description: "Commentary (multi-line supported)"
        required: false
        type: string

jobs:
  add-bookmark:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Restrict workflow to specific users
    if: github.actor == 'anu-rock'

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: SKIP_POSTINSTALL=1 npm install

      # Step 4: Run the create-bookmark script
      - name: Create bookmark
        run: npm run create-bookmark "${{ github.event.inputs.url }}" "${{ github.event.inputs.commentary }}"

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "AnuRock"
          git config --global user.email "echo@anurock.dev"
          git add .
          git commit -m "Add bookmark"
          git push
